--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 02. 21. 12:05:26
-- Server version: 5.5.5-10.1.38-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE kollokvium;

--
-- Drop table `hallgato`
--
DROP TABLE IF EXISTS hallgato;

--
-- Drop table `jelentkezes`
--
DROP TABLE IF EXISTS jelentkezes;

--
-- Drop table `vizsga`
--
DROP TABLE IF EXISTS vizsga;

--
-- Set default database
--
USE kollokvium;

--
-- Create table `vizsga`
--
CREATE TABLE vizsga (
  id INT(11) NOT NULL AUTO_INCREMENT,
  datum DATE DEFAULT NULL,
  targy VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `jelentkezes`
--
CREATE TABLE jelentkezes (
  id INT(11) NOT NULL AUTO_INCREMENT,
  hallgatoid INT(11) NOT NULL,
  vizsgaid INT(11) NOT NULL,
  jeldatum DATE DEFAULT NULL,
  ledatum DATE DEFAULT NULL,
  igazolt TINYINT(1) DEFAULT NULL,
  jegy INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `hallgato`
--
CREATE TABLE hallgato (
  id VARCHAR(255) NOT NULL,
  nev VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table vizsga
--
-- Table kollokvium.vizsga does not contain any data (it is empty)

-- 
-- Dumping data for table jelentkezes
--
-- Table kollokvium.jelentkezes does not contain any data (it is empty)

-- 
-- Dumping data for table hallgato
--
-- Table kollokvium.hallgato does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;